In [1]:
import pandas as pd

In [2]:
novalink_df = pd.read_csv('data/NovaLink_Telecom_Dirty_Exploration_Dataset.csv')

In [14]:
novalink_df.shape

(5000, 26)

In [4]:
novalink_df.head(2)

,customer_id,subscription_id,product_id,phone_number,customer_name,gender,age_group,city,region,customer_segment,...,monthly_price,data_usage_mb,voice_minutes,sms_count,monthly_bill,payment_method,network_type,average_signal_strength_dbm,complaints_count,service_rating
0,CUST00001,SUB00001,PROD002,2348043756984,Customer 1,male,18-25,Kano,North West,premium,...,12000,2146,NaN,233,12000.0,NaN,4g,NaN,NaN,5.0
1,CUST00002,SUB00002,PROD004,2348095683063,Customer 2,NaN,26-35,Port Harcourt,North Central,NaN,...,35000,NaN,3162.0,291,35000.0,Card,3G,-77.0,0.0,3.0

In [5]:
novalink_df.tail()

,customer_id,subscription_id,product_id,phone_number,customer_name,gender,age_group,city,region,customer_segment,...,monthly_price,data_usage_mb,voice_minutes,sms_count,monthly_bill,payment_method,network_type,average_signal_strength_dbm,complaints_count,service_rating
4995,CUST04996,SUB04996,PROD004,2348051843618,Customer 4996,Male,18-25,Kano,North Central,Premium,...,35000,65889,3900.0,226,NaN,USSD,3G,NaN,5.0,4.0
4996,CUST04997,SUB04997,PROD003,2348038576108,Customer 4997,male,36-45,lagos,North Central,Basic,...,18000,45000MB,2073.0,777,18000.0,bank transfer,LTE,-101.0,2.0,4.0
4997,CUST04998,SUB04998,PROD003,2348072642090,Customer 4998,Male,46-60,Ibadan,North West,Standard,...,18000,14795,NaN,66,18000.0,NaN,4g,NaN,1.0,3.0
4998,CUST04999,SUB04999,PROD003,2348029950713,Customer 4999,NaN,NaN,NaN,North West,Standard,...,18000,NaN,NaN,462,NaN,Bank Transfer,3G,-71.0,0.0,5.0
4999,CUST05000,SUB05000,PROD002,2348081318684,Customer 5000,Female,60+,portharcourt,North West,NaN,...,12000,NaN,759.0,367,12000.0,Cash,4G,-68.0,2.0,4.0

In [10]:
novalink_df.sample(5)

,customer_id,subscription_id,product_id,phone_number,customer_name,gender,age_group,city,region,customer_segment,...,monthly_price,data_usage_mb,voice_minutes,sms_count,monthly_bill,payment_method,network_type,average_signal_strength_dbm,complaints_count,service_rating
1376,CUST01377,SUB01377,PROD001,2348059955477,Customer 1377,F,NaN,Kano,North Central,STANDARD,...,25000,8742,NaN,750,NaN,bank transfer,NaN,-54.0,5.0,5.0
1890,CUST01891,SUB01891,PROD001,2348081324025,Customer 1891,Female,NaN,portharcourt,North Central,STANDARD,...,25000,NaN,NaN,739,25000.0,Card,LTE,-999.0,1.0,NaN
3606,CUST03607,SUB03607,PROD003,2348029097731,Customer 3607,Male,46-60,Ibadan,South South,Basic,...,18000,NaN,NaN,66,18000.0,Bank Transfer,3G,NaN,2.0,4.0
2611,CUST02612,SUB02612,PROD005,2348094285415,Customer 2612,M,26-35,lagos,South West,Corporate,...,8000,73548,NaN,561,8000.0,Cash,3G,-999.0,2.0,3.0
3110,CUST03111,SUB03111,PROD004,2348015918144,Customer 3111,M,26-35,portharcourt,South South,STANDARD,...,35000,3594,NaN,420,NaN,CARD,4G,-102.0,NaN,3.0

In [15]:
novalink_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 26 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   customer_id                  5000 non-null   str
 1   subscription_id              5000 non-null   str
 2   product_id                   5000 non-null   str
 3   phone_number                 5000 non-null   int64
 4   customer_name                5000 non-null   str
 5   gender                       4548 non-null   str
 6   age_group                    4148 non-null   str
 7   city                         4551 non-null   str
 8   region                       5000 non-null   str
 9   customer_segment             4294 non-null   str
 10  subscription_start_date      5000 non-null   str
 11  subscription_status          4495 non-null   str
 12  plan_type                    5000 non-null   str
 13  contract_type                5000 non-null   str
 14  product_name                 5000 non-null   str
 15  product_category             5000 non-null   str
 16  monthly_price                5000 non-null   int64
 17  data_usage_mb                3336 non-null   str
 18  voice_minutes                2556 non-null   float64
 19  sms_count                    5000 non-null   int64
 20  monthly_bill                 3312 non-null   float64
 21  payment_method               4340 non-null   str
 22  network_type                 4160 non-null   str
 23  average_signal_strength_dbm  3297 non-null   float64
 24  complaints_count             4020 non-null   float64
 25  service_rating               4172 non-null   float64
dtypes: float64(5), int64(3), str(18)
memory usage: 1015.8 KB

In [18]:
novalink_df.columns

Index(['customer_id', 'subscription_id', 'product_id', 'phone_number',
       'customer_name', 'gender', 'age_group', 'city', 'region',
       'customer_segment', 'subscription_start_date', 'subscription_status',
       'plan_type', 'contract_type', 'product_name', 'product_category',
       'monthly_price', 'data_usage_mb', 'voice_minutes', 'sms_count',
       'monthly_bill', 'payment_method', 'network_type',
       'average_signal_strength_dbm', 'complaints_count', 'service_rating'],
      dtype='str')